### ISSUE TITLE
Url missing in installation page?

### ISSUE THREAD

**Issue by vincentvanhees** [obiba/opal-doc#21]
In http://opaldoc.obiba.org/en/latest/admin/installation.html
there seem to be url links missing for the following lines:

"Manage Opal Service: after package installation, Opal server is running: see how to manage the Service."
"Manage Opal Service: after package installation, Opal is running: see how to manage the Service."

I went through the opal installation process. I am guessing that these missing links will tell me what the next step is in using Opal.

**Comment by ymarcon** [comment]
Thanks it's fixed.
