### ISSUE TITLE
Wrong upgrade package

### ISSUE THREAD

**Issue by AlexisLessard** [obiba/opal-doc#6]
On [this page](http://opaldoc.obiba.org/en/latest/admin/installation.html#upgrade), the following command is used to instigate an upgrade:
```bash
yum install opal
```
However, the `opal` package is not available on the `bintray--obiba-rpm` repository. The package used to install the application is `opal-server`. Maybe that's the one that should be shown? The `opal` could also be associated to the Open Phone Abstraction Library. This should be corrected.

**Comment by ymarcon** [comment]
Fixed, thanks for the report.
