### ISSUE TITLE
Absent mentionned section for HTTPS configuration

### ISSUE THREAD

**Issue by AlexisLessard** [obiba/opal-doc#7]
On [this page](http://opaldoc.obiba.org/en/latest/admin/configuration.html), the **HTTPS Configuration** section is mentioned, but is nowhere to be found. It is not disclosed how to configure custom TLS certificates for Opal, and I've yet to find a setting in the configuration files that helps me. Can this section be added, it possible?

**Comment by kazoompa** [comment]
It is possibly this link that has to be used: http://opaldoc.obiba.org/en/latest/admin/configuration.html#reverse-proxy-configuration

**Comment by kazoompa** [comment]
FYI, all documentation issues will be revised and modified as soon as we get the chance. Thanks for reporting.

**Comment by ymarcon** [comment]
See Encryption Keys section. This is where the key pair is to be provided for enabling a valid (not self-signed) direct (i.e. no reverse proxy) HTTPS connection.

**Comment by djuarezgf** [comment]
Is there any folder where we could put our own certificate for Opal or should the certificate be installed manually through the GUI of Opal (or through the REST-API)?
